### ISSUE TITLE
[request] please upload the kali-dark shell-theme too. 

### ISSUE THREAD

**Issue by kheshav-coder** [SofianeHamlaoui/Kali-Dark#1]
thank you very much for this theme, i've been searching this every where, please upload the shell theme too.

**Comment by AnonymousRonin** [comment]
There's no such thing.  You set the appearance in your qt5settings.

**Comment by AnonymousRonin** [comment]
This doesn't work by the way.  You'll need to copy and paste the code below in mousepad and save it as Kali-Dark.conf and then just add it to the other color config files where you want to use it.  Generally, /usr/share/qt5c.t/colors/then the .conf files.   There should be three lines in total, *active colors *disabled colors * insactive colors  There will be 21 entries per line, all ending with #80ffffff

[ColorScheme]
active_colors=#ffffffff, #ff1c2029, #ff3c4150, #ff21242d, #ff050609, #ff15171e, #ffffffff, #ffffffff, #ffffffff, #ff272a34, #ff23252e, #ffe7e4e0, #ff2777ff, #fff9f9f9, #ff2777ff, #ff2777ff, #ff21242d, #ffffffff, #ff23252e, #ffffffff, #80ffffff
disabled_colors=#ff808080, #ff1c2029, #ff3c4150, #ff21242d, #ff050609, #ff15171e, #ff808080, #ffffffff, #ff808080, #ff272a34, #ff23252e, #ffe7e4e0, #ff2777ff, #ff808080, #ff2777ff, #ff2777ff, #ff21242d, #ffffffff, #ff23252e, #ffffffff, #80ffffff
inactive_colors=#ffffffff, #ff1c2029, #ff3c4150, #ff21242d, #ff050609, #ff15171e, #ffffffff, #ffffffff, #ffffffff, #ff272a34, #ff23252e, #ffe7e4e0, #ff2777ff, #fff9f9f9, #ff2777ff, #ff2777ff, #ff21242d, #ffffffff, #ff23252e, #ffffffff, #80ffffff
